name: Scheduled Maintenance Tasks

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  daily-maintenance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run maintenance tasks
        run: |
          echo "Starting daily maintenance tasks..."
          date
          echo "Performing cleanup operations..."
          # Create a log file
          echo "Maintenance Log - $(date)" > maintenance.log
          echo "Task 1: Cleanup completed" >> maintenance.log
          echo "Task 2: Verification completed" >> maintenance.log
          
      - name: Backup data
        run: |
          echo "Creating backup..." | tee -a maintenance.log
          mkdir -p backups
          echo "Backup created on $(date)" > backups/backup-$(date +%Y%m%d).txt
          echo "Backup file created: backups/backup-$(date +%Y%m%d).txt" >> maintenance.log
          
      # Upload the log file as artifact
      - name: Upload maintenance logs
        if: always()  # Runs even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: maintenance-logs-${{ github.run_number }}
          path: |
            maintenance.log
            backups/*.txt
          retention-days: 30
          
      - name: Success notification
        if: success()
        run: |
          echo "✅ Scheduled tasks completed successfully at $(date)"
          
      - name: Failure notification
        if: failure()
        run: |
          echo "❌ Scheduled tasks failed at $(date)"

  weekly-report:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 3 * * 0'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate weekly report
        run: |
          echo "=== Weekly Report ===" > weekly-report.txt
          echo "Generated: $(date)" >> weekly-report.txt
          echo "Week ending: $(date)" >> weekly-report.txt
          echo "Status: All systems operational" >> weekly-report.txt
          echo "" >> weekly-report.txt
          echo "Tasks completed this week:" >> weekly-report.txt
          echo "- Daily maintenance: 7 runs" >> weekly-report.txt
          echo "- Backups created: 7" >> weekly-report.txt
          cat weekly-report.txt
          
      - name: Upload weekly report
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report-${{ github.run_number }}
          path: weekly-report.txt
          retention-days: 30
